### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by GreyEcologist** [infogram/infogram-node#3]
the inform-methods.js includes a couple of issues with the params = {},
if you remove the '={}' it works fine.

**Comment by GreyEcologist** [comment]
Also, it's related but after making that change, if I want the pdf version of the graph, how do I go about it?
`
infogram.getProject('108719dd-d342-46d5-97b0-a20ad1d15d91', {'format' : 'pdf'}).then(function(data) {
  console.log(data);
}, function(err) {
  console.error(err);
});
`
I tried this but it doesn't look like it captures the params, so the fix I suggested doesn't seem to work.

**Comment by torbjon** [comment]
@GreyEcologist please check master and exmples, there are `png` example.
thanks for comment

**Comment by GreyEcologist** [comment]
Hey Torbon, got busy with something else, sorry about that. I tried with the example file you prodived but I still get the same error:

```
/Users/garethkmensah/Desktop/infogram-node-master/src/infogram-methods.js:10
  getProject: function (id, params = {}) {
                                   ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/garethkmensah/Desktop/infogram-node-master/src/server.js:2:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```
