### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by GreyEcologist** [infogram/infogram-node#5]
see #3 Still getting the same error:

```
/Users/garethkmensah/Desktop/infogram-node-master/src/infogram-methods.js:10
  getProject: function (id, params = {}) {
                                   ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/garethkmensah/Desktop/infogram-node-master/src/server.js:2:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by GreyEcologist** [comment]
Ok, never mind, I had an older version of node.js. Thanks anyway.
