### ISSUE TITLE
Error when deleting project

### ISSUE THREAD

**Issue by jjzcru** [infogram/infogram-node#7]
When i try do delete the project using deleteProject(id) it returns an error TypeError: Cannot read property 'format' of undefined. This error only happens when i try do delete.

`
TypeError: Cannot read property 'format' of undefined
      at Object.call (node_modules\infogram\src\infogram-api.js:50:41)
      at Object.delete (node_modules\infogram\src\infogram-api.js:35:17)
      at Object.deleteProject (node_modules\infogram\src\infogram-methods.js:15:23)
      at Observable._subscribe (dist\data\services\InfogramService.js:102:26)
      at Observable._trySubscribe (node_modules\@reactivex\rxjs\dist\cjs\Observable.js:57:25)
      at Observable.subscribe (node_modules\@reactivex\rxjs\dist\cjs\Observable.js:45:27)
      at Context.<anonymous> (dist\test\integration\data\service\InfogramService.test.js:72:49)
`

**Comment by jjzcru** [comment]
One way you could fix it is changing the file infogram-methods.js from this:
```js
deleteProject: function(id) {
        return this.delete('infographics/' + id);
}
```
to this:
```js
deleteProject: function(id) {
        return this.delete('infographics/' + id, {});
}
```
